services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    ports:
      - "${DOCKER_DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgAdmin:
    container_name: pgAdmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  nginx:
    container_name: nginx
    image: nginx:1.25.5-alpine
    volumes:
      - ./:/var/www
      - ./docker/web-server:/etc/nginx/conf.d
    expose:
      - "80"

  php:
    container_name: php
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www

  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  caddy_data:
  caddy_config:
